language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"
  - "pypy3"

jobs:
  include:
    - if: tag =~ /^([0-9]+\.[0-9]+\.[0-9]+)(\.?(dev|a|b|rc)[0-9]+)?$/
      name: "Linux wheels"
      services:
        - "docker"
      python: "3.8"
      install:
        - python3 -m pip install cibuildwheel==1.6.2 twine virtualenv
      script:
        - export CIBW_BEFORE_BUILD="pip install cython==0.29.16 && cython {project}/jq.pyx"
        - export CIBW_TEST_REQUIRES="-r test-requirements.txt"
        - export CIBW_TEST_COMMAND="nosetests {project}/tests"
        - python3 -m cibuildwheel --output-dir wheelhouse &&
          twine check wheelhouse/*.whl &&
          twine upload wheelhouse/*.whl --skip-existing

    - if: tag =~ /^([0-9]+\.[0-9]+\.[0-9]+)(\.?(dev|a|b|rc)[0-9]+)?$/
      name: "OS X wheels"
      os: osx
      osx_image: xcode11.2
      language: "shell"
      install:
        - python3 -m pip install cibuildwheel==1.6.2 twine virtualenv
      script:
        - export CIBW_BEFORE_BUILD="pip install cython==0.29.16 && cython {project}/jq.pyx"
        - export CIBW_TEST_REQUIRES="-r test-requirements.txt"
        - export CIBW_TEST_COMMAND="nosetests {project}/tests"
        - python3 -m cibuildwheel --output-dir wheelhouse &&
          twine check wheelhouse/*.whl &&
          twine upload wheelhouse/*.whl --skip-existing

env:
  global:
    - TWINE_USERNAME=__token__
    # Note: TWINE_PASSWORD is set to a PyPI API token in Travis settings

install:
  - "make jq.c"
  - "pip install tox"
script: tox -e py
